server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
     defaultZone: http://localhost:10086/euteka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false # 关闭自我保护模式
    eviction-interval-timer-in-ms: 10000    # 10